In [ ]:
import json
import ssl
import urllib.parse
import urllib.request

import certifi

params = urllib.parse.urlencode(
    {
        "start": "1",
        "limit": "15", # Number of cryptocurrencies to return
        "convert": "USD",
    }
)

request = urllib.request.Request(
    f"https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?{params}",
    headers={
        "Accept": "application/json",
        "X-CMC_PRO_API_KEY": "75c74e39420443718582207851d06134",
    },
)

context = ssl.create_default_context(cafile=certifi.where())

with urllib.request.urlopen(request, context=context) as response:
    data = json.load(response)

print(data)

{'data': [{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'infinite_supply': False, 'circulating_supply': 20025871, 'total_supply': 20025871, 'max_supply': 21000000, 'date_added': '2010-07-13T00:00:00.000Z', 'num_market_pairs': 12624, 'cmc_rank': 1, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 1626167173577.49, 'quote': {'USD': {'price': 81203.31812671186, 'volume_24h': 39674727277.978455, 'cex_volume_24h': 39619374760.14601, 'dex_volume_24h': 55352517.83244054, 'volume_change_24h': -1.2553, 'percent_change_1h': -0.38595786, 'percent_change_24h': -0.89358488, 'percent_change_7d': 6.79352031, 'percent_change_30d': 17.78496593, 'percent_change_60d': 20.25183179, 'percent_change_90d': 25.15693181, 'market_cap': 1626167173577.4934, 'market_cap_dominance': 60.3749, 'fully_diluted_market_cap': 1705269680660.95, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'infinite_supply': True, 'circulating_supply': 120687104.06368364, 'total_supply': 120687104.06368364, 'max_supply': None, 'date_added': '2015-08-07T00:00:00.000Z', 'num_market_pairs': 11926, 'cmc_rank': 2, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 281594562975.54, 'quote': {'USD': {'price': 2333.261413141158, 'volume_24h': 24238451615.924572, 'cex_volume_24h': 24092197643.111343, 'dex_volume_24h': 146253972.813233, 'volume_change_24h': 40.4539, 'percent_change_1h': -0.48193888, 'percent_change_24h': -2.50653109, 'percent_change_7d': 3.43304038, 'percent_change_30d': 10.34155327, 'percent_change_60d': 19.09611878, 'percent_change_90d': 24.48270648, 'market_cap': 281594562975.5445, 'market_cap_dominance': 10.4548, 'fully_diluted_market_cap': 281594562975.54, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'ethereum-pow-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'world-liberty-financial-portfolio', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'abstract-chain-ecosystem', 'unichain-ecosystem', 'soneium-ecosystem', 'sophon-ecosystem', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'infinite_supply': True, 'circulating_supply': 189651082316.74588, 'total_supply': 194203497624.11526, 'max_supply': None, 'date_added': '2015-02-25T00:00:00.000Z', 'num_market_pairs': 180652, 'cmc_rank': 3, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': {'id': 1027, 'slug': 'ethereum', 'name': 'Ethereum', 'symbol': 'ETH', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 194150240280.45, 'quote': {'USD': {'price': 0.9997257652703794, 'volume_24h': 134525838226.70692, 'cex_volume_24h': 131414164681.3777, 'dex_volume_24h': 3111673545.329411, 'volume_change_24h': -0.6031, 'percent_change_1h': -0.01647494, 'percent_change_24h': -0.00737892, 'percent_change_7d': 0.02163296, 'percent_change_30d': -0.01142381, 'percent_change_60d': -0.01422151, 'percent_change_90d': 0.10222055, 'market_cap': 189599073403.46448, 'market_cap_dominance': 7.037, 'fully_diluted_market_cap': 194150240280.45, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['stablecoin', 'asset-backed-stablecoin', 'usd-stablecoin', 'ethereum-pow-ecosystem', 'fiat-stablecoin', 'tron20-ecosystem', 'rsk-rbtc-ecosystem', 'venom-ecosystem', 'world-liberty-financial-portfolio', 'binance-ecosystem', 'binance-listing', 'peaq-ecosystem', 'apertum-ecosystem', 'etherlink-ecosystem', 'duckchain-ecosystem', 'onus-ecosystem', 'sophon-ecosystem', 'zedxion-smart-chain-ecosystem', 'xlayer-ecosystem']}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'infinite_supply': False, 'circulating_supply': 134785807.62, 'total_supply': 134785807.62, 'max_supply': 134785807.62, 'date_added': '2017-07-25T00:00:00.000Z', 'num_market_pairs': 3218, 'cmc_rank': 4, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 87702935438.59, 'quote': {'USD': {'price': 650.6837551164721, 'volume_24h': 2365617894.041742, 'cex_volume_24h': 2345917392.798112, 'dex_volume_24h': 19700501.24362999, 'volume_change_24h': 24.6948, 'percent_change_1h': -0.19830876, 'percent_change_24h': 0.78487958, 'percent_change_7d': 5.54536812, 'percent_change_30d': 8.04797264, 'percent_change_60d': 5.03323017, 'percent_change_90d': 5.11089051, 'market_cap': 87702935438.588, 'market_cap_dominance': 3.2562, 'fully_diluted_market_cap': 87702936805.02, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate', 'binance-ecosystem', 'binance-listing', 'etherlink-ecosystem', 'made-in-china']}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'infinite_supply': False, 'circulating_supply': 61796225236, 'total_supply': 99985670046, 'max_supply': 100000000000, 'date_added': '2013-08-04T00:00:00.000Z', 'num_market_pairs': 1830, 'cmc_rank': 5, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 141606122804.42, 'quote': {'USD': {'price': 1.4162641780494025, 'volume_24h': 2741695026.3754225, 'cex_volume_24h': 2740440876.3801665, 'dex_volume_24h': 1254149.99525557, 'volume_change_24h': 16.0932, 'percent_change_1h': -0.25285693, 'percent_change_24h': -1.79318798, 'percent_change_7d': 3.18863529, 'percent_change_30d': 7.34010524, 'percent_change_60d': 4.1666865, 'percent_change_90d': 8.85913726, 'market_cap': 87519780140.41928, 'market_cap_dominance': 3.2494, 'fully_diluted_market_cap': 141626417804.94, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'solana-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'iso-20022', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'infinite_supply': False, 'circulating_supply': 78288621225.84703, 'total_supply': 78288621225.84703, 'max_supply': None, 'date_added': '2018-10-08T00:00:00.000Z', 'num_market_pairs': 39298, 'cmc_rank': 6, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': {'id': 1027, 'slug': 'ethereum', 'name': 'Ethereum', 'symbol': 'ETH', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'self_reported_circulating_supply': 60901219650.23, 'self_reported_market_cap': 60885222719.95057, 'minted_market_cap': 78268057144.82, 'quote': {'USD': {'price': 0.9997373298864735, 'volume_24h': 50351139185.30758, 'cex_volume_24h': 48131869331.566605, 'dex_volume_24h': 2219269853.7409525, 'volume_change_24h': -17.2407, 'percent_change_1h': -0.01445103, 'percent_change_24h': -0.00434362, 'percent_change_7d': -0.01287523, 'percent_change_30d': 0.00262206, 'percent_change_60d': -0.02334547, 'percent_change_90d': -0.01270242, 'market_cap': 78268057144.82181, 'market_cap_dominance': 2.9066, 'fully_diluted_market_cap': 78268057144.82, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'stellar-ecosystem', 'coinbase-ventures-portfolio', 'usd-stablecoin', 'xdc-ecosystem', 'ethereum-pow-ecosystem', 'fiat-stablecoin', 'tron20-ecosystem', 'venom-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio', 'sonic-ecosystem', 'binance-ecosystem', 'binance-listing', 'hyperevm-ecosystem', 'etherlink-ecosystem', 'unichain-ecosystem', 'vector-smart-chain-ecosystem', 'sophon-ecosystem', 'monad-ecosystem', 'xlayer-ecosystem']}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'infinite_supply': True, 'circulating_supply': 577082598.6120179, 'total_supply': 625832369.0461907, 'max_supply': None, 'date_added': '2020-04-10T00:00:00.000Z', 'num_market_pairs': 1126, 'cmc_rank': 7, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': 525236893.3, 'self_reported_market_cap': 47032067167.05689, 'minted_market_cap': 56039837246.33, 'quote': {'USD': {'price': 89.54448510187488, 'volume_24h': 5577228881.332335, 'cex_volume_24h': 5577195407.319158, 'dex_volume_24h': 33474.0131782, 'volume_change_24h': 12.9311, 'percent_change_1h': -0.59719568, 'percent_change_24h': 0.58187986, 'percent_change_7d': 7.7529228, 'percent_change_30d': 11.72233993, 'percent_change_60d': 7.82278023, 'percent_change_90d': 13.35534747, 'market_cap': 51674564153.96507, 'market_cap_dominance': 1.9179, 'fully_diluted_market_cap': 56039837246.33, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities', 'coinlist-launchpad']}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'infinite_supply': True, 'circulating_supply': 94793458796.4234, 'total_supply': 94793459584.5634, 'max_supply': None, 'date_added': '2017-09-13T00:00:00.000Z', 'num_market_pairs': 1338, 'cmc_rank': 8, 'last_updated': '2026-05-07T09:01:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': 94667886298.43, 'self_reported_market_cap': 32665900470.26066, 'minted_market_cap': 32709230522.58, 'quote': {'USD': {'price': 0.3450578833806961, 'volume_24h': 742888566.7162131, 'cex_volume_24h': 742772500.0250621, 'dex_volume_24h': 116066.69115102, 'volume_change_24h': -17.8454, 'percent_change_1h': 0.1755526, 'percent_change_24h': 0.6852709, 'percent_change_7d': 6.31770868, 'percent_change_30d': 9.15735625, 'percent_change_60d': 20.37748898, 'percent_change_90d': 28.25349239, 'market_cap': 32709230250.629086, 'market_cap_dominance': 1.2144, 'fully_diluted_market_cap': 32709230522.58, 'tvl': None, 'last_updated': '2026-05-07T09:01:00.000Z'}}, 'tags': ['media', 'payments', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio', 'binance-ecosystem', 'binance-listing', 'made-in-china']}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'infinite_supply': True, 'circulating_supply': 169848823126.57913, 'total_supply': 169848823126.57913, 'max_supply': None, 'date_added': '2013-12-15T00:00:00.000Z', 'num_market_pairs': 1439, 'cmc_rank': 9, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 18942079586.33, 'quote': {'USD': {'price': 0.11152317241673733, 'volume_24h': 2211855842.4032316, 'cex_volume_24h': 2210565374.632582, 'dex_volume_24h': 1290467.77064916, 'volume_change_24h': -2.7757, 'percent_change_1h': -0.0982464, 'percent_change_24h': -4.47209895, 'percent_change_7d': 4.31314505, 'percent_change_30d': 22.61466205, 'percent_change_60d': 24.84637682, 'percent_change_90d': 22.93074019, 'market_cap': 18942079586.325405, 'market_cap_dominance': 0.7033, 'fully_diluted_market_cap': 18942079586.33, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'doge-chain-ecosystem', 'osmosis-ecosystem', 'ftx-bankruptcy-estate', 'animal-memes', 'made-in-america', 'binance-ecosystem', 'binance-listing', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 32196, 'name': 'Hyperliquid', 'symbol': 'HYPE', 'slug': 'hyperliquid', 'infinite_supply': False, 'circulating_supply': 254985404.56732497, 'total_supply': 955260239.4390464, 'max_supply': 961671487.86, 'date_added': '2024-07-15T10:14:50.000Z', 'num_market_pairs': 259, 'cmc_rank': 10, 'last_updated': '2026-05-07T09:00:00.000Z', 'tvl_ratio': None, 'platform': {'id': 32196, 'slug': 'hyperliquid', 'name': 'Hyperliquid', 'symbol': 'HYPE', 'token_address': '0x0d01dc56dcaaca66ad901c959b4011ec'}, 'self_reported_circulating_supply': 333931719, 'self_reported_market_cap': 14315655790.538515, 'minted_market_cap': 40952015038.13, 'quote': {'USD': {'price': 42.870008974914164, 'volume_24h': 412874464.9193114, 'cex_volume_24h': 339904173.65692425, 'dex_volume_24h': 72970291.26238725, 'volume_change_24h': 5.3215, 'percent_change_1h': -0.97273767, 'percent_change_24h': -3.3116619, 'percent_change_7d': 9.0274639, 'percent_change_30d': 17.64305606, 'percent_change_60d': 41.56164869, 'percent_change_90d': 31.88409273, 'market_cap': 10931226582.27334, 'market_cap_dominance': 0.4058, 'fully_diluted_market_cap': 41226865315.48, 'tvl': None, 'last_updated': '2026-05-07T09:00:00.000Z'}}, 'tags': ['decentralized-exchange-dex-token', 'defi', 'derivatives', 'layer-1', 'hyperliquid-ecosystem', 'binance-ecosystem', 'binance-listing', 'perp-dex-coins']}], 'status': {'timestamp': '2026-05-07T09:02:07.285Z', 'error_code': 0, 'error_message': None, 'elapsed': 5, 'credit_count': 1, 'total_count': 8461, 'notice': None}}

【结论】拉取出的数据是JSON格式，不方便观看，需要标准化Normalize.
【注意】输出数据是字典格式key-value pairs，顶层有一个键key "data"，其值value是一个列表。列表中的每个元素是一个字典。探索 JSON 数据结构的关键是 逐层打印 和 格式化输出Normalize，结合 Pandas 的 json_normalize 或调试工具，可以快速理解复杂的嵌套结构。

In [2]:
type(data)

dict

In [ ]:
import pandas as pd

pd.json_normalize(data["data"])

,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,...,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address
0,1,Bitcoin,BTC,bitcoin,False,2.002587e+07,2.002587e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12624,...,1.626167e+12,60.3749,1.705270e+12,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,True,1.206871e+08,1.206871e+08,NaN,2015-08-07T00:00:00.000Z,11926,...,2.815946e+11,10.4548,2.815946e+11,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,True,1.896511e+11,1.942035e+11,NaN,2015-02-25T00:00:00.000Z,180652,...,1.895991e+11,7.0370,1.941502e+11,None,2026-05-07T09:00:00.000Z,1027.0,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7
3,1839,BNB,BNB,bnb,False,1.347858e+08,1.347858e+08,1.347858e+08,2017-07-25T00:00:00.000Z,3218,...,8.770294e+10,3.2562,8.770294e+10,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN
4,52,XRP,XRP,xrp,False,6.179623e+10,9.998567e+10,1.000000e+11,2013-08-04T00:00:00.000Z,1830,...,8.751978e+10,3.2494,1.416264e+11,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN
5,3408,USDC,USDC,usd-coin,False,7.828862e+10,7.828862e+10,NaN,2018-10-08T00:00:00.000Z,39298,...,7.826806e+10,2.9066,7.826806e+10,None,2026-05-07T09:00:00.000Z,1027.0,ethereum,Ethereum,ETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
6,5426,Solana,SOL,solana,True,5.770826e+08,6.258324e+08,NaN,2020-04-10T00:00:00.000Z,1126,...,5.167456e+10,1.9179,5.603984e+10,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN
7,1958,TRON,TRX,tron,True,9.479346e+10,9.479346e+10,NaN,2017-09-13T00:00:00.000Z,1338,...,3.270923e+10,1.2144,3.270923e+10,None,2026-05-07T09:01:00.000Z,NaN,NaN,NaN,NaN,NaN
8,74,Dogecoin,DOGE,dogecoin,True,1.698488e+11,1.698488e+11,NaN,2013-12-15T00:00:00.000Z,1439,...,1.894208e+10,0.7033,1.894208e+10,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN
9,32196,Hyperliquid,HYPE,hyperliquid,False,2.549854e+08,9.552602e+08,9.616715e+08,2024-07-15T10:14:50.000Z,259,...,1.093123e+10,0.4058,4.122687e+10,None,2026-05-07T09:00:00.000Z,32196.0,hyperliquid,Hyperliquid,HYPE,0x0d01dc56dcaaca66ad901c959b4011ec

调取网站中最新更新时间，以首行item的最新更新时间为例

In [4]:
pd.to_datetime(data["data"][0]["quote"]["USD"]["last_updated"])

Timestamp('2026-05-07 09:00:00+0000', tz='UTC')

【结论】更新时间为：0507 上午九点，timezone 时区为UTC

添加用户调取时间列"timestamp"

In [5]:
# 创建dataframe来承接标准化后的数据集，然后添加一个新的列来记录当前的时间戳

df = pd.json_normalize(data["data"])
df['timestamp'] = pd.to_datetime('now')
df

,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,...,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,False,2.002587e+07,2.002587e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12624,...,60.3749,1.705270e+12,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
1,1027,Ethereum,ETH,ethereum,True,1.206871e+08,1.206871e+08,NaN,2015-08-07T00:00:00.000Z,11926,...,10.4548,2.815946e+11,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
2,825,Tether USDt,USDT,tether,True,1.896511e+11,1.942035e+11,NaN,2015-02-25T00:00:00.000Z,180652,...,7.0370,1.941502e+11,None,2026-05-07T09:00:00.000Z,1027.0,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7,2026-05-07 17:37:50.466081
3,1839,BNB,BNB,bnb,False,1.347858e+08,1.347858e+08,1.347858e+08,2017-07-25T00:00:00.000Z,3218,...,3.2562,8.770294e+10,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
4,52,XRP,XRP,xrp,False,6.179623e+10,9.998567e+10,1.000000e+11,2013-08-04T00:00:00.000Z,1830,...,3.2494,1.416264e+11,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
5,3408,USDC,USDC,usd-coin,False,7.828862e+10,7.828862e+10,NaN,2018-10-08T00:00:00.000Z,39298,...,2.9066,7.826806e+10,None,2026-05-07T09:00:00.000Z,1027.0,ethereum,Ethereum,ETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2026-05-07 17:37:50.466081
6,5426,Solana,SOL,solana,True,5.770826e+08,6.258324e+08,NaN,2020-04-10T00:00:00.000Z,1126,...,1.9179,5.603984e+10,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
7,1958,TRON,TRX,tron,True,9.479346e+10,9.479346e+10,NaN,2017-09-13T00:00:00.000Z,1338,...,1.2144,3.270923e+10,None,2026-05-07T09:01:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
8,74,Dogecoin,DOGE,dogecoin,True,1.698488e+11,1.698488e+11,NaN,2013-12-15T00:00:00.000Z,1439,...,0.7033,1.894208e+10,None,2026-05-07T09:00:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 17:37:50.466081
9,32196,Hyperliquid,HYPE,hyperliquid,False,2.549854e+08,9.552602e+08,9.616715e+08,2024-07-15T10:14:50.000Z,259,...,0.4058,4.122687e+10,None,2026-05-07T09:00:00.000Z,32196.0,hyperliquid,Hyperliquid,HYPE,0x0d01dc56dcaaca66ad901c959b4011ec,2026-05-07 17:37:50.466081

自动化流程

In [ ]:
import os
import json
import ssl
import urllib.parse
import urllib.request
import pandas as pd
import certifi
from time import sleep

df = pd.DataFrame()  # 初始化为空 DataFrame

def api_runner():
    
    global df # 声明df为全局变量，以便在函数内修改它

    params = urllib.parse.urlencode(
        {
            "start": "1",
            "limit": "15", # Number of cryptocurrencies to return
            "convert": "USD",
        }
    )

    request = urllib.request.Request(
        f"https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?{params}",
        headers={
            "Accept": "application/json",
            "X-CMC_PRO_API_KEY": "75c74e39420443718582207851d06134",
        },
    )

    context = ssl.create_default_context(cafile=certifi.where())

    with urllib.request.urlopen(request, context=context) as response:
        data = json.load(response)

    print(data)

    df2 = pd.json_normalize(data["data"])
    df2['timestamp'] = pd.to_datetime('now')

    df = pd.concat([df, df2], ignore_index=True) # 将新数据追加到现有的dataframe中
    
    # 写入 CSV 文件
    if not os.path.exists('crypto_data.csv'): # 如果csv文件不存在，则创建并写入数据；如果存在，则追加数据；在代码中没有明确指定 CSV 文件的路径，那么文件会被创建在 当前工作目录 下。
        df.to_csv('crypto_data.csv', header='column_names', index=False)
    else:
        df.to_csv('crypto_data.csv', mode='w', header=False, index=False)

In [33]:
import os
from time import time
from time import sleep

for i in range(300): # Loop to run the API call 300 times
    api_runner() # Call the function to execute the API call and process the data
    print(f"Iteration {i+1} completed. Sleeping for 60 seconds...") # Print the iteration number and sleep message
    sleep(60) # Sleep for 60 seconds before the next API call
exit()

{'data': [{'id': 1, 'name': 'Bitcoin', 'symbol': 'BTC', 'slug': 'bitcoin', 'infinite_supply': False, 'circulating_supply': 20025915, 'total_supply': 20025915, 'max_supply': 21000000, 'date_added': '2010-07-13T00:00:00.000Z', 'num_market_pairs': 12625, 'cmc_rank': 1, 'last_updated': '2026-05-07T10:39:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 1617081999332.86, 'quote': {'USD': {'price': 80749.46884239065, 'volume_24h': 37974494314.62053, 'cex_volume_24h': 37922105408.33813, 'dex_volume_24h': 52388906.28239761, 'volume_change_24h': -9.8239, 'percent_change_1h': -0.20959241, 'percent_change_24h': -1.82881863, 'percent_change_7d': 6.17651009, 'percent_change_30d': 17.78910348, 'percent_change_60d': 18.79202842, 'percent_change_90d': 22.5387373, 'market_cap': 1617081999332.8635, 'market_cap_dominance': 60.3954, 'fully_diluted_market_cap': 1695738845690.2, 'tvl': None, 'last_updated': '2026-05-07T10:39:00.000Z'}}, 'tags': ['mineable', 'pow', 'sha-256', 'store-of-value', 'state-channel', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'galaxy-digital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'bitcoin-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 1027, 'name': 'Ethereum', 'symbol': 'ETH', 'slug': 'ethereum', 'infinite_supply': True, 'circulating_supply': 120687104.06368364, 'total_supply': 120687104.06368364, 'max_supply': None, 'date_added': '2015-08-07T00:00:00.000Z', 'num_market_pairs': 11926, 'cmc_rank': 2, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 280408928336.37, 'quote': {'USD': {'price': 2323.4373756155505, 'volume_24h': 22739538747.43732, 'cex_volume_24h': 22595659115.44786, 'dex_volume_24h': 143879631.98945284, 'volume_change_24h': 17.8168, 'percent_change_1h': -0.33692307, 'percent_change_24h': -3.63134006, 'percent_change_7d': 2.71624104, 'percent_change_30d': 10.59671479, 'percent_change_60d': 17.7243573, 'percent_change_90d': 20.77333809, 'market_cap': 280408928336.36597, 'market_cap_dominance': 10.4763, 'fully_diluted_market_cap': 280408928336.37, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['pos', 'smart-contracts', 'ethereum-ecosystem', 'coinbase-ventures-portfolio', 'three-arrows-capital-portfolio', 'polychain-capital-portfolio', 'binance-labs-portfolio', 'blockchain-capital-portfolio', 'boostvc-portfolio', 'cms-holdings-portfolio', 'dcg-portfolio', 'dragonfly-capital-portfolio', 'electric-capital-portfolio', 'fabric-ventures-portfolio', 'framework-ventures-portfolio', 'hashkey-capital-portfolio', 'kenetic-capital-portfolio', 'huobi-capital-portfolio', 'alameda-research-portfolio', 'a16z-portfolio', '1confirmation-portfolio', 'winklevoss-capital-portfolio', 'usv-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'multicoin-capital-portfolio', 'paradigm-portfolio', 'ethereum-pow-ecosystem', 'layer-1', 'ftx-bankruptcy-estate', 'sora-ecosystem', 'rsk-rbtc-ecosystem', 'world-liberty-financial-portfolio', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'abstract-chain-ecosystem', 'unichain-ecosystem', 'soneium-ecosystem', 'sophon-ecosystem', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 825, 'name': 'Tether USDt', 'symbol': 'USDT', 'slug': 'tether', 'infinite_supply': True, 'circulating_supply': 189651082316.74588, 'total_supply': 194203497624.11526, 'max_supply': None, 'date_added': '2015-02-25T00:00:00.000Z', 'num_market_pairs': 180689, 'cmc_rank': 3, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': {'id': 1027, 'slug': 'ethereum', 'name': 'Ethereum', 'symbol': 'ETH', 'token_address': '0xdac17f958d2ee523a2206206994597c13d831ec7'}, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 194150869628.63, 'quote': {'USD': {'price': 0.9997290059338518, 'volume_24h': 130182173727.08072, 'cex_volume_24h': 127079886237.11058, 'dex_volume_24h': 3102287489.970299, 'volume_change_24h': -8.2064, 'percent_change_1h': -0.00010589, 'percent_change_24h': -0.00066858, 'percent_change_7d': 0.00169353, 'percent_change_30d': -0.0029915, 'percent_change_60d': -0.024585, 'percent_change_90d': 0.10220172, 'market_cap': 189599687998.79944, 'market_cap_dominance': 7.0819, 'fully_diluted_market_cap': 194150869628.63, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['stablecoin', 'asset-backed-stablecoin', 'usd-stablecoin', 'ethereum-pow-ecosystem', 'fiat-stablecoin', 'tron20-ecosystem', 'rsk-rbtc-ecosystem', 'venom-ecosystem', 'world-liberty-financial-portfolio', 'binance-ecosystem', 'binance-listing', 'peaq-ecosystem', 'apertum-ecosystem', 'etherlink-ecosystem', 'duckchain-ecosystem', 'onus-ecosystem', 'sophon-ecosystem', 'zedxion-smart-chain-ecosystem', 'xlayer-ecosystem']}, {'id': 1839, 'name': 'BNB', 'symbol': 'BNB', 'slug': 'bnb', 'infinite_supply': False, 'circulating_supply': 134785803.55, 'total_supply': 134785803.55, 'max_supply': 134785803.55, 'date_added': '2017-07-25T00:00:00.000Z', 'num_market_pairs': 3218, 'cmc_rank': 4, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 87184466678.11, 'quote': {'USD': {'price': 646.837162236959, 'volume_24h': 2252019942.9887075, 'cex_volume_24h': 2233290908.309189, 'dex_volume_24h': 18729034.67951792, 'volume_change_24h': 11.9793, 'percent_change_1h': -0.38596844, 'percent_change_24h': -0.02217677, 'percent_change_7d': 5.00412195, 'percent_change_30d': 7.70411239, 'percent_change_60d': 3.78114179, 'percent_change_90d': 2.08390034, 'market_cap': 87184466678.11023, 'market_cap_dominance': 3.2573, 'fully_diluted_market_cap': 87184466678.11, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['marketplace', 'centralized-exchange', 'payments', 'smart-contracts', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'bnb-chain-ecosystem', 'layer-1', 'alleged-sec-securities', 'celsius-bankruptcy-estate', 'binance-ecosystem', 'binance-listing', 'etherlink-ecosystem', 'made-in-china']}, {'id': 52, 'name': 'XRP', 'symbol': 'XRP', 'slug': 'xrp', 'infinite_supply': False, 'circulating_supply': 61796225236, 'total_supply': 99985670046, 'max_supply': 100000000000, 'date_added': '2013-08-04T00:00:00.000Z', 'num_market_pairs': 1830, 'cmc_rank': 5, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 140805105900.58, 'quote': {'USD': {'price': 1.4082528609929759, 'volume_24h': 2550894699.8408637, 'cex_volume_24h': 2550049688.5819974, 'dex_volume_24h': 845011.25886605, 'volume_change_24h': -0.2847, 'percent_change_1h': -0.34216001, 'percent_change_24h': -2.88825424, 'percent_change_7d': 2.72168588, 'percent_change_30d': 7.33694254, 'percent_change_60d': 2.90223597, 'percent_change_90d': 2.23735145, 'market_cap': 87024710987.16333, 'market_cap_dominance': 3.2513, 'fully_diluted_market_cap': 140825286099.3, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['medium-of-exchange', 'enterprise-solutions', 'xrp-ecosystem', 'solana-ecosystem', 'arrington-xrp-capital-portfolio', 'galaxy-digital-portfolio', 'a16z-portfolio', 'pantera-capital-portfolio', 'ftx-bankruptcy-estate', '2017-2018-alt-season', 'klaytn-ecosystem', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'iso-20022', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 3408, 'name': 'USDC', 'symbol': 'USDC', 'slug': 'usd-coin', 'infinite_supply': False, 'circulating_supply': 78297212068.0313, 'total_supply': 78297212068.0313, 'max_supply': None, 'date_added': '2018-10-08T00:00:00.000Z', 'num_market_pairs': 39304, 'cmc_rank': 6, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': {'id': 1027, 'slug': 'ethereum', 'name': 'Ethereum', 'symbol': 'ETH', 'token_address': '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48'}, 'self_reported_circulating_supply': 60901219650.23, 'self_reported_market_cap': 60887329643.40481, 'minted_market_cap': 78279354481.33, 'quote': {'USD': {'price': 0.9997719256378614, 'volume_24h': 49225928014.69399, 'cex_volume_24h': 47023636654.04536, 'dex_volume_24h': 2202291360.648592, 'volume_change_24h': -22.2166, 'percent_change_1h': 0.00228677, 'percent_change_24h': 0.00205494, 'percent_change_7d': -0.02942179, 'percent_change_30d': -0.00062115, 'percent_change_60d': -0.0237733, 'percent_change_90d': -0.01007496, 'market_cap': 78279354481.33165, 'market_cap_dominance': 2.9236, 'fully_diluted_market_cap': 78279354481.33, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['medium-of-exchange', 'stablecoin', 'asset-backed-stablecoin', 'stellar-ecosystem', 'coinbase-ventures-portfolio', 'usd-stablecoin', 'xdc-ecosystem', 'ethereum-pow-ecosystem', 'fiat-stablecoin', 'tron20-ecosystem', 'venom-ecosystem', 'made-in-america', 'world-liberty-financial-portfolio', 'sonic-ecosystem', 'binance-ecosystem', 'binance-listing', 'hyperevm-ecosystem', 'etherlink-ecosystem', 'unichain-ecosystem', 'vector-smart-chain-ecosystem', 'sophon-ecosystem', 'monad-ecosystem', 'xlayer-ecosystem']}, {'id': 5426, 'name': 'Solana', 'symbol': 'SOL', 'slug': 'solana', 'infinite_supply': True, 'circulating_supply': 577082555.2899904, 'total_supply': 625832325.7241632, 'max_supply': None, 'date_added': '2020-04-10T00:00:00.000Z', 'num_market_pairs': 1126, 'cmc_rank': 7, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': 525236893.3, 'self_reported_market_cap': 46692564464.42705, 'minted_market_cap': 55635307773.61, 'quote': {'USD': {'price': 88.89810495044112, 'volume_24h': 5224105551.73123, 'cex_volume_24h': 5224072612.299737, 'dex_volume_24h': 32939.43149326, 'volume_change_24h': -2.6592, 'percent_change_1h': -0.66524655, 'percent_change_24h': -0.75782659, 'percent_change_7d': 7.1156903, 'percent_change_30d': 11.49204285, 'percent_change_60d': 6.00460999, 'percent_change_90d': 9.05568093, 'market_cap': 51301545565.23831, 'market_cap_dominance': 1.9162, 'fully_diluted_market_cap': 55635307773.61, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['pos', 'platform', 'solana-ecosystem', 'cms-holdings-portfolio', 'kenetic-capital-portfolio', 'alameda-research-portfolio', 'multicoin-capital-portfolio', 'okx-ventures-portfolio', 'layer-1', 'ftx-bankruptcy-estate', 'alleged-sec-securities', 'cmc-crypto-awards-2024', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities', 'coinlist-launchpad']}, {'id': 1958, 'name': 'TRON', 'symbol': 'TRX', 'slug': 'tron', 'infinite_supply': True, 'circulating_supply': 94793439233.194, 'total_supply': 94793439299.8739, 'max_supply': None, 'date_added': '2017-09-13T00:00:00.000Z', 'num_market_pairs': 1338, 'cmc_rank': 8, 'last_updated': '2026-05-07T10:39:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': 94667886298.43, 'self_reported_market_cap': 32844501945.39174, 'minted_market_cap': 32888061868, 'quote': {'USD': {'price': 0.3469444943753481, 'volume_24h': 739063275.9299171, 'cex_volume_24h': 738921950.9859319, 'dex_volume_24h': 141324.9439852, 'volume_change_24h': -18.3747, 'percent_change_1h': 0.47990611, 'percent_change_24h': 1.02662376, 'percent_change_7d': 6.4627293, 'percent_change_30d': 10.1092449, 'percent_change_60d': 20.8463951, 'percent_change_90d': 28.77210482, 'market_cap': 32888061844.860775, 'market_cap_dominance': 1.2283, 'fully_diluted_market_cap': 32888061868, 'tvl': None, 'last_updated': '2026-05-07T10:39:00.000Z'}}, 'tags': ['media', 'payments', 'tron-ecosystem', 'layer-1', 'dwf-labs-portfolio', 'alleged-sec-securities', '2017-2018-alt-season', 'tron20-ecosystem', 'world-liberty-financial-portfolio', 'binance-ecosystem', 'binance-listing', 'made-in-china']}, {'id': 74, 'name': 'Dogecoin', 'symbol': 'DOGE', 'slug': 'dogecoin', 'infinite_supply': True, 'circulating_supply': 154137816383.70526, 'total_supply': 154137816383.70526, 'max_supply': None, 'date_added': '2013-12-15T00:00:00.000Z', 'num_market_pairs': 1439, 'cmc_rank': 9, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 17098943082.33, 'quote': {'USD': {'price': 0.11093282286913046, 'volume_24h': 2130749518.2483068, 'cex_volume_24h': 2129458069.2050307, 'dex_volume_24h': 1291449.04327609, 'volume_change_24h': -12.2291, 'percent_change_1h': -0.54051817, 'percent_change_24h': -4.49579324, 'percent_change_7d': 4.00527815, 'percent_change_30d': 22.35187321, 'percent_change_60d': 22.08737791, 'percent_change_90d': 18.86245872, 'market_cap': 17098943082.328129, 'market_cap_dominance': 0.6386, 'fully_diluted_market_cap': 17098943082.33, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['mineable', 'pow', 'scrypt', 'medium-of-exchange', 'memes', 'payments', 'doggone-doggerel', 'doge-chain-ecosystem', 'osmosis-ecosystem', 'ftx-bankruptcy-estate', 'animal-memes', 'made-in-america', 'binance-ecosystem', 'binance-listing', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 32196, 'name': 'Hyperliquid', 'symbol': 'HYPE', 'slug': 'hyperliquid', 'infinite_supply': False, 'circulating_supply': 254984037.5119077, 'total_supply': 955258705.0495961, 'max_supply': 961671487.86, 'date_added': '2024-07-15T10:14:50.000Z', 'num_market_pairs': 259, 'cmc_rank': 10, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': {'id': 32196, 'slug': 'hyperliquid', 'name': 'Hyperliquid', 'symbol': 'HYPE', 'token_address': '0x0d01dc56dcaaca66ad901c959b4011ec'}, 'self_reported_circulating_supply': 333931719, 'self_reported_market_cap': 14205099940.851702, 'minted_market_cap': 40635688682.81, 'quote': {'USD': {'price': 42.53893575426329, 'volume_24h': 396013855.5579461, 'cex_volume_24h': 324758838.21573216, 'dex_volume_24h': 71255017.3422139, 'volume_change_24h': 3.3627, 'percent_change_1h': -0.77521698, 'percent_change_24h': -3.99155726, 'percent_change_7d': 8.80779182, 'percent_change_30d': 16.38098639, 'percent_change_60d': 39.30595866, 'percent_change_90d': 26.78708397, 'market_cap': 10846749590.081703, 'market_cap_dominance': 0.4051, 'fully_diluted_market_cap': 40908481638.78, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['decentralized-exchange-dex-token', 'defi', 'derivatives', 'layer-1', 'hyperliquid-ecosystem', 'binance-ecosystem', 'binance-listing', 'perp-dex-coins']}, {'id': 2010, 'name': 'Cardano', 'symbol': 'ADA', 'slug': 'cardano', 'infinite_supply': False, 'circulating_supply': 36193530883.92486, 'total_supply': 44993540553.74233, 'max_supply': 45000000000, 'date_added': '2017-10-01T00:00:00.000Z', 'num_market_pairs': 1706, 'cmc_rank': 11, 'last_updated': '2026-05-07T10:39:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': 37997904336, 'self_reported_market_cap': 10123423083.888645, 'minted_market_cap': 11987204426.85, 'quote': {'USD': {'price': 0.2664205634703255, 'volume_24h': 536837430.78453434, 'cex_volume_24h': 536016397.75621635, 'dex_volume_24h': 821033.02831827, 'volume_change_24h': -18.5547, 'percent_change_1h': -0.26675847, 'percent_change_24h': -1.6773901, 'percent_change_7d': 8.32554917, 'percent_change_30d': 9.92868846, 'percent_change_60d': 3.99137662, 'percent_change_90d': 1.85976575, 'market_cap': 9642700892.07589, 'market_cap_dominance': 0.3601, 'fully_diluted_market_cap': 11988925356.16, 'tvl': None, 'last_updated': '2026-05-07T10:39:00.000Z'}}, 'tags': ['dpos', 'pos', 'platform', 'research', 'smart-contracts', 'staking', 'cardano-ecosystem', 'cardano', 'layer-1', 'alleged-sec-securities', '2017-2018-alt-season', 'made-in-america', 'us-strategic-crypto-reserve', 'binance-ecosystem', 'binance-listing', 'iso-20022', 'sec-cftc-token-taxonomy', 'sec-cftc-digital-commodities']}, {'id': 3957, 'name': 'UNUS SED LEO', 'symbol': 'LEO', 'slug': 'unus-sed-leo', 'infinite_supply': False, 'circulating_supply': 920676774.9, 'total_supply': 985239504, 'max_supply': None, 'date_added': '2019-05-21T00:00:00.000Z', 'num_market_pairs': 68, 'cmc_rank': 12, 'last_updated': '2026-05-07T10:39:00.000Z', 'tvl_ratio': None, 'platform': {'id': 1027, 'slug': 'ethereum', 'name': 'Ethereum', 'symbol': 'ETH', 'token_address': '0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3'}, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 10197301005.02, 'quote': {'USD': {'price': 10.350073219374924, 'volume_24h': 438757.54017828, 'cex_volume_24h': 438732.31513578, 'dex_volume_24h': 25.22504251, 'volume_change_24h': -13.856, 'percent_change_1h': 0.00102411, 'percent_change_24h': 0.03289564, 'percent_change_7d': -0.23382908, 'percent_change_30d': 2.56920231, 'percent_change_60d': 14.54664769, 'percent_change_90d': 54.59765343, 'market_cap': 9529072031.592966, 'market_cap_dominance': 0.3559, 'fully_diluted_market_cap': 10197301005.02, 'tvl': None, 'last_updated': '2026-05-07T10:39:00.000Z'}}, 'tags': ['marketplace', 'centralized-exchange', 'discount-token', 'payments', 'ethereum-ecosystem', 'kenetic-capital-portfolio', 'alameda-research-portfolio']}, {'id': 1437, 'name': 'Zcash', 'symbol': 'ZEC', 'slug': 'zcash', 'infinite_supply': False, 'circulating_supply': 16663615.5405448, 'total_supply': 16663748.9155448, 'max_supply': 21000000, 'date_added': '2016-10-29T00:00:00.000Z', 'num_market_pairs': 604, 'cmc_rank': 13, 'last_updated': '2026-05-07T10:38:00.000Z', 'tvl_ratio': None, 'platform': None, 'self_reported_circulating_supply': None, 'self_reported_market_cap': None, 'minted_market_cap': 9473390638.43, 'quote': {'USD': {'price': 568.5029633154388, 'volume_24h': 1144717885.9375794, 'cex_volume_24h': 1127566569.4330451, 'dex_volume_24h': 17151316.50453428, 'volume_change_24h': -34.9731, 'percent_change_1h': 0.88317811, 'percent_change_24h': -1.67164252, 'percent_change_7d': 70.78504094, 'percent_change_30d': 113.5457917, 'percent_change_60d': 185.62114597, 'percent_change_90d': 156.89904636, 'market_cap': 9473314814.348917, 'market_cap_dominance': 0.3538, 'fully_diluted_market_cap': 11938562229.62, 'tvl': None, 'last_updated': '2026-05-07T10:38:00.000Z'}}, 'tags': ['mineable', 'pow', 'equihash', 'medium-of-exchange', 'privacy', 'zero-knowledge-proofs', 'quantum-resistant', 'binance-chain', 'boostvc-portfolio', 'dcg-portfolio', 'electric-capital-portfolio', 'fenbushi-capital-portfolio', 'hashkey-capital-portfolio', 'winklevoss-capital-portfolio', 'placeholder-ventures-portfolio', 'pantera-capital-portfolio', 'layer-1', 'standard-crypto-portfolio', '2017-2018-alt-season', 'made-in-america', 'binance-ecosystem', 'binance-listing', 'privacy-coins']}, {'id': 1831, 'name': 'Bitcoin Cash', 'symbol': 'BCH', 'slug': 'bitcoin-cash', 'infinite_supply': False, 'circulating_supply': 20031181.25, 'total_supply': 20031181.25, 'max_supply': 21000000, 'date_added': '2017-07-23T00:00

KeyboardInterrupt:

In [34]:
df

,id,name,symbol,slug,infinite_supply,circulating_supply,total_supply,max_supply,date_added,num_market_pairs,...,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.slug,platform.name,platform.symbol,platform.token_address,timestamp
0,1,Bitcoin,BTC,bitcoin,False,2.002592e+07,2.002592e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12625,...,60.3954,1.695739e+12,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
1,1027,Ethereum,ETH,ethereum,True,1.206871e+08,1.206871e+08,NaN,2015-08-07T00:00:00.000Z,11926,...,10.4763,2.804089e+11,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
2,825,Tether USDt,USDT,tether,True,1.896511e+11,1.942035e+11,NaN,2015-02-25T00:00:00.000Z,180689,...,7.0819,1.941509e+11,None,2026-05-07T10:38:00.000Z,1027.0,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7,2026-05-07 18:40:31.332194
3,1839,BNB,BNB,bnb,False,1.347858e+08,1.347858e+08,1.347858e+08,2017-07-25T00:00:00.000Z,3218,...,3.2573,8.718447e+10,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
4,52,XRP,XRP,xrp,False,6.179623e+10,9.998567e+10,1.000000e+11,2013-08-04T00:00:00.000Z,1830,...,3.2513,1.408253e+11,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
5,3408,USDC,USDC,usd-coin,False,7.829721e+10,7.829721e+10,NaN,2018-10-08T00:00:00.000Z,39304,...,2.9236,7.827935e+10,None,2026-05-07T10:38:00.000Z,1027.0,ethereum,Ethereum,ETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2026-05-07 18:40:31.332194
6,5426,Solana,SOL,solana,True,5.770826e+08,6.258323e+08,NaN,2020-04-10T00:00:00.000Z,1126,...,1.9162,5.563531e+10,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
7,1958,TRON,TRX,tron,True,9.479344e+10,9.479344e+10,NaN,2017-09-13T00:00:00.000Z,1338,...,1.2283,3.288806e+10,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
8,74,Dogecoin,DOGE,dogecoin,True,1.541378e+11,1.541378e+11,NaN,2013-12-15T00:00:00.000Z,1439,...,0.6386,1.709894e+10,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
9,32196,Hyperliquid,HYPE,hyperliquid,False,2.549840e+08,9.552587e+08,9.616715e+08,2024-07-15T10:14:50.000Z,259,...,0.4051,4.090848e+10,None,2026-05-07T10:38:00.000Z,32196.0,hyperliquid,Hyperliquid,HYPE,0x0d01dc56dcaaca66ad901c959b4011ec,2026-05-07 18:40:31.332194
10,2010,Cardano,ADA,cardano,False,3.619353e+10,4.499354e+10,4.500000e+10,2017-10-01T00:00:00.000Z,1706,...,0.3601,1.198893e+10,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
11,3957,UNUS SED LEO,LEO,unus-sed-leo,False,9.206768e+08,9.852395e+08,NaN,2019-05-21T00:00:00.000Z,68,...,0.3559,1.019730e+10,None,2026-05-07T10:39:00.000Z,1027.0,ethereum,Ethereum,ETH,0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3,2026-05-07 18:40:31.332194
12,1437,Zcash,ZEC,zcash,False,1.666362e+07,1.666375e+07,2.100000e+07,2016-10-29T00:00:00.000Z,604,...,0.3538,1.193856e+10,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
13,1831,Bitcoin Cash,BCH,bitcoin-cash,False,2.003118e+07,2.003118e+07,2.100000e+07,2017-07-23T00:00:00.000Z,1159,...,0.3432,9.634974e+09,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
14,328,Monero,XMR,monero,True,1.844674e+07,1.844674e+07,NaN,2014-05-21T00:00:00.000Z,368,...,0.2829,7.571118e+09,None,2026-05-07T10:38:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:40:31.332194
15,1,Bitcoin,BTC,bitcoin,False,2.002592e+07,2.002592e+07,2.100000e+07,2010-07-13T00:00:00.000Z,12625,...,60.3954,1.695739e+12,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
16,1027,Ethereum,ETH,ethereum,True,1.206871e+08,1.206871e+08,NaN,2015-08-07T00:00:00.000Z,11926,...,10.4728,2.804072e+11,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
17,825,Tether USDt,USDT,tether,True,1.896511e+11,1.942035e+11,NaN,2015-02-25T00:00:00.000Z,180689,...,7.0820,1.941526e+11,None,2026-05-07T10:39:00.000Z,1027.0,ethereum,Ethereum,ETH,0xdac17f958d2ee523a2206206994597c13d831ec7,2026-05-07 18:41:32.403775
18,1839,BNB,BNB,bnb,False,1.347858e+08,1.347858e+08,1.347858e+08,2017-07-25T00:00:00.000Z,3218,...,3.2563,8.718698e+10,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
19,52,XRP,XRP,xrp,False,6.179623e+10,9.998567e+10,1.000000e+11,2013-08-04T00:00:00.000Z,1830,...,3.2503,1.408279e+11,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
20,3408,USDC,USDC,usd-coin,False,7.829721e+10,7.829721e+10,NaN,2018-10-08T00:00:00.000Z,39304,...,2.9238,7.828482e+10,None,2026-05-07T10:39:00.000Z,1027.0,ethereum,Ethereum,ETH,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2026-05-07 18:41:32.403775
21,5426,Solana,SOL,solana,True,5.770826e+08,6.258323e+08,NaN,2020-04-10T00:00:00.000Z,1126,...,1.9163,5.563693e+10,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
22,1958,TRON,TRX,tron,True,9.479344e+10,9.479344e+10,NaN,2017-09-13T00:00:00.000Z,1338,...,1.2284,3.289143e+10,None,2026-05-07T10:40:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
23,74,Dogecoin,DOGE,dogecoin,True,1.541378e+11,1.541378e+11,NaN,2013-12-15T00:00:00.000Z,1439,...,0.6386,1.709911e+10,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
24,32196,Hyperliquid,HYPE,hyperliquid,False,2.549840e+08,9.552587e+08,9.616715e+08,2024-07-15T10:14:50.000Z,259,...,0.4051,4.091435e+10,None,2026-05-07T10:39:00.000Z,32196.0,hyperliquid,Hyperliquid,HYPE,0x0d01dc56dcaaca66ad901c959b4011ec,2026-05-07 18:41:32.403775
25,2010,Cardano,ADA,cardano,False,3.619353e+10,4.499354e+10,4.500000e+10,2017-10-01T00:00:00.000Z,1706,...,0.3605,1.199948e+10,None,2026-05-07T10:40:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
26,3957,UNUS SED LEO,LEO,unus-sed-leo,False,9.206768e+08,9.852395e+08,NaN,2019-05-21T00:00:00.000Z,68,...,0.3558,1.019728e+10,None,2026-05-07T10:40:00.000Z,1027.0,ethereum,Ethereum,ETH,0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3,2026-05-07 18:41:32.403775
27,1437,Zcash,ZEC,zcash,False,1.666362e+07,1.666375e+07,2.100000e+07,2016-10-29T00:00:00.000Z,604,...,0.3531,1.191305e+10,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
28,1831,Bitcoin Cash,BCH,bitcoin-cash,False,2.003118e+07,2.003118e+07,2.100000e+07,2017-07-23T00:00:00.000Z,1159,...,0.3432,9.634836e+09,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775
29,328,Monero,XMR,monero,True,1.844674e+07,1.844674e+07,NaN,2014-05-21T00:00:00.000Z,368,...,0.2827,7.568091e+09,None,2026-05-07T10:39:00.000Z,NaN,NaN,NaN,NaN,NaN,2026-05-07 18:41:32.403775